-- ui_theme.lua  —  auto-generated by tools/generate_themes.py
-- Theme: jeuno
-- Drop into themes/jeuno/ and GearTree will apply it when the theme is active.
--
-- All keys must match cfg keys in ui_facelift.lua.
-- Panel/bg colors: { alpha, r, g, b }  |  Text colors: { r, g, b }

local theme = {
    active_title_bg          = {185, 88,  68, 20},
    active_title_fg          = {252, 230, 168},
    border_light             = {200,182, 148, 48},
    border_shadow            = {180,145, 112, 30},
    divider_col              = {145,148, 120, 42},
    header_bg                = {180, 12, 22, 44},
    header_fg                = {235, 214, 162},
    row_bg_cursor            = {192,  42,  72,120},
    row_bg_hover             = {140,  42,  72,108},
    row_fg_cat               = {145, 188, 225},
    row_fg_cursor            = {252, 238, 168},
    row_fg_set               = {218, 208, 192},
    tab_hover_bg             = {140, 48,  72,110},
    title_fg                 = {222, 195, 155},
}

return theme
